import type { LeadRow } from "@/lib/leads/types";

/** Minimal LeadRow for unit/component tests — override fields as needed. */
export function makeLead(overrides: Partial<LeadRow> = {}): LeadRow {
  return {
    id: "lead-1",
    org_id: "org-1",
    email: "test@example.com",
    ghl_contact_id: null,
    name: "Test Lead",
    phone: "+911234567890",
    created_at: "2026-01-01T00:00:00.000Z",
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    utm_content: null,
    utm_term: null,
    ad_set_id: null,
    lead_source: null,
    form_filled_at: "2026-01-01T00:00:00.000Z",
    custom_fields: {},
    qualified: null,
    qualified_at: null,
    qualified_by: null,
    call_booked_at: null,
    call_scheduled_for: null,
    cal_com_booking_id: null,
    booking_source: null,
    booking_history: [],
    call_cancelled_at: null,
    setter_verified: null,
    setter_verified_at: null,
    setter_verified_by: null,
    verification_call_status: "not_contacted",
    verification_call_attempts: 0,
    last_verification_call_at: null,
    reminder_sent: false,
    reminder_sent_at: null,
    call_showed: null,
    call_showed_at: null,
    call_showed_by: null,
    deal_closed: null,
    deal_value: null,
    closed_at: null,
    closed_by: null,
    notes: null,
    recording_url: null,
    stage: "form_filled",
    requalification_attempted: false,
    requalification_called_at: null,
    requalification_result: null,
    requalification_notes: null,
    post_call_status: null,
    post_call_status_updated_at: null,
    post_call_status_updated_by: null,
    lifecycle_status: "active",
    action_status: null,
    is_dead: false,
    dead_reason: null,
    contact_attempts: 0,
    call_confirmed: null,
    next_action_at: null,
    last_action: null,
    last_action_at: null,
    updated_at: "2026-01-01T00:00:00.000Z",
    slack_form_notified: false,
    slack_booking_notified: false,
    slack_no_booking_notified: false,
    ...overrides
  };
}
